name: secrets-practice

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: self-hosted
    steps:
      - name: Print Secret (safe way)
        run: echo "Secret is set!"
      
      - name: Use Secret in Script
        run: |
          echo "Using secret in script..."
          echo "${{ secrets.MY_SECRET }}" | wc -c
