name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          else
            echo "Docker credentials not set. Skipping login."
          fi

      - name: Build and push Docker image
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Building and pushing image..."
            docker build -t "${{ secrets.DOCKER_USERNAME }}/hcl-getaction:latest" .
            docker push "${{ secrets.DOCKER_USERNAME }}/hcl-getaction:latest"
          else
            echo "Docker username not set. Skipping build and push."
          fi
